# This is a basic GitHub Actions workflow file that sets up status checks
name: CI

# This workflow will run whenever code is pushed or a pull request is created
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    # The type of machine to run this job on
    runs-on: ubuntu-latest

    # Steps to run in the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build script
      - name: Build project
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm test
